version: "3.9"
services:

  rust-bench:
    image: rust-bench
    build: ./Rust/
    volumes:
      - type: bind
        source: ./Rust/criterion
        target: /causal-hub/target/criterion
    command: cargo bench
    
  r-bench:
    image: r-bench
    build: ./R/
    volumes:
      - type: bind
        source: ./R/
        target: /causal-hub/R/
    command: Rscript ./R/bnlearn_benches.r
